/*==============================================================================================================================
| Author        Ignia, LLC
| Client        Goldsim
| Project       Website
\=============================================================================================================================*/
using GoldSim.Web.Administration.Models.Invoices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace GoldSim.Web.Models.Forms.BindingModels {

  /*============================================================================================================================
  | BINDING MODEL: PAYMENT FORM
  \---------------------------------------------------------------------------------------------------------------------------*/
  /// <summary>
  ///   Provides a strongly-typed binding model representing the pay invoice form.
  /// </summary>
  public class PaymentFormBindingModel {

    /*==========================================================================================================================
    | CONSTRUCTOR
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   Initializes a new instance of a <see cref="PaymentFormBindingModel"/> object.
    /// </summary>
    public PaymentFormBindingModel() : base() {
    }

    /*==========================================================================================================================
    | PROPERTY: CARDHOLDER NAME
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   Gets or sets the name on the credit card being paid with.
    /// </summary>
    [Display(Name="Cardholder Name")]
    public string CardholderName { get; set; }

    /*==========================================================================================================================
    | PROPERTY: ORGANIZATION
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   Gets or sets the user's organization or institution name.
    /// </summary>
    [Required]
    [StringLength(255)]
    [Display(Name = "Organization Name")]
    public virtual string Organization { get; set; }

    /*==========================================================================================================================
    | PROPERTY: EMAIL ADDRESS
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   Gets or sets the user's email address.
    /// </summary>
    [Required]
    [EmailAddress]
    [Display(Name = "Email Address")]
    public virtual string Email { get; set; }

    /*==========================================================================================================================
    | INVOICE NUMBER
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   The unique identifier generated by GoldSim's invoicing software and used to track payments back to purchases.
    /// </summary>
    [Required]
    [Range(1000, 99999)]
    [Display(Name="Invoice Number")]
    public int InvoiceNumber { get; set; }

    /*==========================================================================================================================
    | INVOICE AMOUNT
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   The amount due on the invoice, in United States Dollars (USD).
    /// </summary>
    [Required]
    [Range(1.00, 1000000.00)]
    [Display(Name = "Invoice Amount")]
    public double InvoiceAmount { get; set; }

    /*==========================================================================================================================
    | PROPERTY: PAYMENT METHOD NONCE
    \-------------------------------------------------------------------------------------------------------------------------*/
    /// <summary>
    ///   The authorization nonce returned from the PayPal web service.
    /// </summary>
    [Required(ErrorMessage="The credit card information is required.")]
    public string PaymentMethodNonce { get; set; }

  } //Class

} //Namespace